# Generated by Django 4.1.2 on 2024-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('countryName', models.TextField()),
                ('year1', models.TextField()),
                ('year2', models.TextField()),
                ('year3', models.TextField()),
                ('year4', models.TextField()),
                ('year5', models.TextField()),
            ],
        ),
    ]
