# Generated by Django 4.1.2 on 2024-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_output_year6_alter_output_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='year6',
            field=models.TextField(),
        ),
    ]
