# Generated by Django 4.1.2 on 2024-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0003_alter_output_year6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
