# Generated by Django 4.1.2 on 2024-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0004_alter_output_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.TextField()),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField()),
                ('year3', models.IntegerField()),
                ('year4', models.IntegerField()),
                ('year5', models.IntegerField()),
                ('year6', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataCountries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.TextField()),
                ('incomeGroup', models.TextField()),
                ('specialNotes', models.TextField()),
                ('tableName', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='output',
        ),
    ]
